# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-09 06:23
from __future__ import unicode_literals

import address.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Election Date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='End Date')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=64, verbose_name='Last Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('umpire_accreditation', models.CharField(choices=[('A', 'A Grade'), ('B', 'B Grade'), ('C', 'C Grade'), ('D', 'D Grade'), ('N', 'None')], default='N', max_length=1, verbose_name='Umpire Accreditation')),
                ('joined', models.DateField(default=datetime.date.today, verbose_name='Join Date')),
                ('updated', models.DateField(auto_now=True, verbose_name='Last Updated')),
                ('media_release', models.BooleanField(default=False, verbose_name='Media Release')),
                ('media_release_date', models.DateField(blank=True, null=True, verbose_name='Media Release Signed Date')),
                ('vanda_policy', models.BooleanField(default=False, verbose_name='Violence and Aggression Policy Agreement')),
                ('vanda_policy_date', models.DateField(blank=True, null=True, verbose_name='Violence and Aggression Policy Agreement Date')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tables', models.PositiveIntegerField(verbose_name='Number of Tables')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_name', models.CharField(blank=True, max_length=128, verbose_name='Contact Name')),
                ('slug', models.SlugField(blank=True)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='address.Address', verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.Player')),
                ('preference', models.CharField(choices=[('M', 'Mobile'), ('E', 'Email')], default='E', max_length=1, verbose_name='Notification Preference')),
                ('events', models.BooleanField(default=True)),
                ('results', models.BooleanField(default=True)),
                ('resources', models.BooleanField(default=True)),
                ('news', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='address.Address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='committee',
            name='assistant_secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_secretary', to='members.Player', verbose_name='Assistant Secretary'),
        ),
        migrations.AddField(
            model_name='committee',
            name='president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='president', to='members.Player', verbose_name='President'),
        ),
        migrations.AddField(
            model_name='committee',
            name='secretary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secretary', to='members.Player', verbose_name='Secretary'),
        ),
        migrations.AddField(
            model_name='committee',
            name='statistician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statistician', to='members.Player', verbose_name='Statistician'),
        ),
        migrations.AddField(
            model_name='committee',
            name='treasurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasurer', to='members.Player', verbose_name='Treasurer'),
        ),
        migrations.AddField(
            model_name='committee',
            name='vice_president',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vice_president', to='members.Player', verbose_name='Vice President'),
        ),
    ]
