# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-18 06:36
from __future__ import unicode_literals

import address.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Election Date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='End Date')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('PR', 'President'), ('VP', 'Vice President'), ('TR', 'Treasurer'), ('ST', 'Statistician'), ('SE', 'Secretary'), ('AS', 'Assistant Secretary')], max_length=2, verbose_name='Committee Position')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='members.Committee', verbose_name='Committee')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=64, verbose_name='Last Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('umpire_accreditation', models.CharField(choices=[('A', 'A Grade'), ('B', 'B Grade'), ('C', 'C Grade'), ('D', 'D Grade'), ('N', 'None')], default='N', max_length=1, verbose_name='Umpire Accreditation')),
                ('joined', models.DateField(default=datetime.date.today, verbose_name='Join Date')),
                ('updated', models.DateField(auto_now=True, verbose_name='Last Updated')),
                ('media_release', models.BooleanField(default=False, verbose_name='Media Release')),
                ('media_release_date', models.DateField(blank=True, null=True, verbose_name='Media Release Signed Date')),
                ('vanda_policy', models.BooleanField(default=False, verbose_name='Violence and Aggression Policy Agreement')),
                ('vanda_policy_date', models.DateField(blank=True, null=True, verbose_name='Violence and Aggression Policy Agreement Date')),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tables', models.PositiveIntegerField(verbose_name='Number of Tables')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_name', models.CharField(blank=True, max_length=128, verbose_name='Contact Name')),
                ('slug', models.SlugField(blank=True)),
                ('address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='address.Address', verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='members.Player')),
                ('preference', models.CharField(choices=[('M', 'Mobile'), ('E', 'Email')], default='E', max_length=1, verbose_name='Notification Preference')),
                ('events', models.BooleanField(default=True)),
                ('results', models.BooleanField(default=True)),
                ('resources', models.BooleanField(default=True)),
                ('news', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='address.Address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='committee', to='members.Player', verbose_name='Member'),
        ),
    ]
