# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=64, verbose_name='Last Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('joined', models.DateField(default=datetime.date.today, verbose_name='Join Date')),
                ('updated', models.DateField(auto_now=True, verbose_name='Last Updated')),
                ('media_release', models.BooleanField(default=False, verbose_name='Media Release')),
                ('umpire_accreditation', models.CharField(choices=[('A', 'A Grade'), ('B', 'B Grade'), ('C', 'C Grade'), ('D', 'D Grade'), ('N', 'None')], default='N', max_length=1, verbose_name='Umpire Accreditation')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
