# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-26 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0009_seasonpage_venueindexpage_venuepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_day', models.CharField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=1)),
                ('open_time', models.CharField(max_length=10)),
                ('close_day', models.CharField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=1)),
                ('close_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VenueDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.CharField(blank=True, max_length=100)),
                ('gmaps_url', models.CharField(blank=True, max_length=100)),
                ('venue_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_details', to='home.VenuePage')),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, max_length=300, upload_to='gmaps_images/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='venues.VenueDetails')),
            ],
        ),
        migrations.AddField(
            model_name='openhours',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openhours', to='venues.VenueDetails'),
        ),
    ]
