# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='title',
            field=models.CharField(default='fuuuuuu', max_length=50, verbose_name='Social Site'),
            preserve_default=False,
        ),
    ]
