# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_copyright'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copyright',
            old_name='copyright',
            new_name='body',
        ),
    ]
