# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='logo',
            new_name='image',
        ),
    ]
