# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('home', '0004_auto_20161201_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContactItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_text', models.CharField(blank=True, max_length=40)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('intro', models.CharField(blank=True, max_length=300)),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_item', to='home.AboutPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
