# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutpagecontactitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontactitem',
            name='icon',
            field=models.CharField(default='facebook', max_length=20, verbose_name='Icon Code (fa)'),
            preserve_default=False,
        ),
    ]
